<?php
/**
 * ACF Definitionen.
 *
 * @package Webwerk
 */

if ( function_exists( 'acf_add_local_field_group' ) ) :

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5eaaca2526635',
			'title'                 => 'Block: Bild mit Copyright',
			'fields'                => array(
				array(
					'key'               => 'field_5eaaca9446481',
					'label'             => 'Bild',
					'name'              => 'img',
					'aria-label'        => '',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'array',
					'preview_size'      => 'medium',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
				array(
					'key'               => 'field_5eaacb7c46484',
					'label'             => 'Bildgröße',
					'name'              => 'img_size',
					'aria-label'        => '',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(),
					'default_value'     => false,
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'label',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_5eb1566dea008',
					'label'             => 'Link zu Original',
					'name'              => 'url_self',
					'aria-label'        => '',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui'                => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'acf/img-copyright',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => false,
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5f05b85b7f50b',
			'title'                 => 'Block: Blog',
			'fields'                => array(),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'acf/blog',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => false,
		)
	);

	acf_add_local_field_group(array(
		'key' => 'group_626410bc30699',
		'title' => 'Block: Bundesliga',
		'fields' => array(
			array(
				'key' => 'field_6264332a9ba68',
				'label' => 'Zeile',
				'name' => 'row',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => '',
				'sub_fields' => array(
					array(
						'key' => 'field_626433b39ba69',
						'label' => 'Platz',
						'name' => 'platz',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_626433c69ba6a',
						'label' => 'Mannschaft',
						'name' => 'mannschaft',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),


					array(
						'key' => 'field_626433e69ba6c',
						'label' => 'Gewonnen',
						'name' => 'gewonnen',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_626433ef9ba6d',
						'label' => 'Unentschieden',
						'name' => 'unentschieden',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_626433fb9ba6e',
						'label' => 'Verloren',
						'name' => 'verloren',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_626432879ba64',
						'label' => 'Tore',
						'name' => 'tore',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),
					array(
						'key' => 'field_626432c99ba65',
						'label' => 'Gegentore',
						'name' => 'gegentore',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),


				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/bundesliga',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));
	acf_add_local_field_group(array(
		'key' => 'group_640f771f90db0',
		'title' => 'Block: Bundesliga PCF',
		'fields' => array(
			array(
				'key' => 'field_640f771f9832b',
				'label' => 'Zeile',
				'name' => 'row',
				'aria-label' => '',
				'type' => 'repeater',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'collapsed' => '',
				'min' => 0,
				'max' => 0,
				'layout' => 'table',
				'button_label' => 'Eintrag hinzufügen',
				'rows_per_page' => 20,
				'sub_fields' => array(
					array(
						'key' => 'field_640f771f9f794',
						'label' => 'Platz',
						'name' => 'platz',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'parent_repeater' => 'field_640f771f9832b',
					),
					array(
						'key' => 'field_640f771fa3313',
						'label' => 'Mannschaft',
						'name' => 'mannschaft',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'parent_repeater' => 'field_640f771f9832b',
					),

					array(
						'key' => 'field_640f771faa7c9',
						'label' => 'Gewonnen',
						'name' => 'gewonnen',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'parent_repeater' => 'field_640f771f9832b',
					),
					array(
						'key' => 'field_640f771fae2b7',
						'label' => 'Unentschieden',
						'name' => 'unentschieden',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'parent_repeater' => 'field_640f771f9832b',
					),
					array(
						'key' => 'field_640f771fb1d51',
						'label' => 'Verloren',
						'name' => 'verloren',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'parent_repeater' => 'field_640f771f9832b',
					),
					array(
						'key' => 'field_640f771fb57d4',
						'label' => 'Tore',
						'name' => 'tore',
						'aria-label' => '',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
						'parent_repeater' => 'field_640f771f9832b',
					),

					array(
						'key' => 'field_626432c99ba65',
						'label' => 'Gegentore',
						'name' => 'gegentore',
						'type' => 'text',
						'instructions' => '',
						'required' => 0,
						'conditional_logic' => 0,
						'wrapper' => array(
							'width' => '',
							'class' => '',
							'id' => '',
						),
						'default_value' => '',
						'placeholder' => '',
						'prepend' => '',
						'append' => '',
						'maxlength' => '',
					),


				),
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'block',
					'operator' => '==',
					'value' => 'acf/bundesliga-pcf',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(
		array(
			'key'                   => 'group_6380d093be07f',
			'title'                 => 'Block: Bundesliga 1Spielplan',
			'fields'                => array(
				array(
					'key'               => 'field_6380d0940e314',
					'label'             => 'Zeile',
					'name'              => 'row',
					'aria-label'        => '',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => '',
					'min'               => 0,
					'max'               => 0,
					'layout'            => 'table',
					'button_label'      => 'Eintrag hinzufügen',
					'rows_per_page'     => 20,
					'sub_fields'        => array(
						array(
							'key'               => 'field_6380d0947fb74',
							'label'             => 'Spielnummer',
							'name'              => 'spielnummer',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
							'parent_repeater'   => 'field_6380d0940e314',
						),
						array(
							'key'               => 'field_6380d09483600',
							'label'             => 'Zeit',
							'name'              => 'zeit',
							'aria-label'        => '',
							'type'              => 'time_picker',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'display_format'    => 'H:i',
							'return_format'     => 'H:i',
							'parent_repeater'   => 'field_6380d0940e314',
						),
						array(
							'key'               => 'field_6380d094870a8',
							'label'             => 'Mannschaft 1',
							'name'              => 'mannschaft_1',
							'aria-label'        => '',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'Black Knights Dreieich 1' => 'Black Knights Dreieich 1',
								'Black Knights Dreieich 2' => 'Black Knights Dreieich 2',
								'Star Drivers Bad Kreuznach' => 'Star Drivers Bad Kreuznach',
								'Rolli Teufel Ludwigshafen' => 'Rolli Teufel Ludwigshafen',
								'Munich Animals'           => 'Munich Animals',
								'Nording Bulls Lalendorf'  => 'Nording Bulls Lalendorf',
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
							'parent_repeater'   => 'field_6380d0940e314',
						),
						array(
							'key'               => 'field_6380d0948ab33',
							'label'             => 'Mannschaft 2',
							'name'              => 'mannschaft_2',
							'aria-label'        => '',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'Black Knights Dreieich 1' => 'Black Knights Dreieich 1',
								'Black Knights Dreieich 2' => 'Black Knights Dreieich 2',
								'Star Drivers Bad Kreuznach' => 'Star Drivers Bad Kreuznach',
								'Rolli Teufel Ludwigshafen' => 'Rolli Teufel Ludwigshafen',
								'Munich Animals'           => 'Munich Animals',
								'Nording Bulls Lalendorf'  => 'Nording Bulls Lalendorf',
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
							'parent_repeater'   => 'field_6380d0940e314',
						),
						array(
							'key'               => 'field_6380a4d1e8bae',
							'label'             => '1. Schiedsrichter',
							'name'              => '1_schiedsrichter',
							'aria-label'        => '',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices' => array(
								'Waldemar Ulrich' => 'Waldemar Ulrich',
								'Gennadi Hill' => 'Gennadi Hill',
								'Gerd Autenrieth' => 'Gerd Autenrieth',
								'Gerd Menz' => 'Gerd Menz',
								'Paul Kirste' => 'Paul Kirste',
								'Nadir Mohamed' => 'Nadir Mohamed',
								'Christoph Respondek' => 'Christoph Respondek',
								'Jürgen Erdmann-Feix' => 'Jürgen Erdmann-Feix',
								'Ralf Buree' => 'Ralf Buree',
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
							'parent_repeater'   => 'field_6380a05b3653a',
						),
						array(
							'key'               => 'field_6380a4ede8baf',
							'label'             => '2. Schiedsrichter',
							'name'              => '2_schiedsrichter',
							'aria-label'        => '',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices' => array(
								'Waldemar Ulrich' => 'Waldemar Ulrich',
								'Gennadi Hill' => 'Gennadi Hill',
								'Gerd Autenrieth' => 'Gerd Autenrieth',
								'Gerd Menz' => 'Gerd Menz',
								'Paul Kirste' => 'Paul Kirste',
								'Nadir Mohamed' => 'Nadir Mohamed',
								'Christoph Respondek' => 'Christoph Respondek',
								'Jürgen Erdmann-Feix' => 'Jürgen Erdmann-Feix',
								'Ralf Buree' => 'Ralf Buree',
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
							'parent_repeater'   => 'field_6380a05b3653a',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'acf/spielplan1liga',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_6380d0a032c33',
			'title'                 => 'Block: Bundesliga 2Spielplan',
			'fields'                => array(
				array(
					'key'               => 'field_6380d0a06bcf5',
					'label'             => 'Zeile',
					'name'              => 'row',
					'aria-label'        => '',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => '',
					'min'               => 0,
					'max'               => 0,
					'layout'            => 'table',
					'button_label'      => 'Eintrag hinzufügen',
					'rows_per_page'     => 20,
					'sub_fields'        => array(
						array(
							'key'               => 'field_6380d0a0cadbc',
							'label'             => 'Spielnummer',
							'name'              => 'spielnummer',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
							'parent_repeater'   => 'field_6380d0a06bcf5',
						),
						array(
							'key'               => 'field_6380d0a0ce99b',
							'label'             => 'Zeit',
							'name'              => 'zeit',
							'aria-label'        => '',
							'type'              => 'time_picker',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'display_format'    => 'H:i',
							'return_format'     => 'H:i',
							'parent_repeater'   => 'field_6380d0a06bcf5',
						),
						array(
							'key'               => 'field_6380d0a0d2442',
							'label'             => 'Mannschaft 1',
							'name'              => 'mannschaft_1',
							'aria-label'        => '',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'Hurricanes Bochum'    => 'Hurricanes Bochum',
								'Flash Tigers'         => 'Flash Tigers',
								'Ruhr Rollers Essen'   => 'Ruhr Rollers Essen',
								'Ballbusters Würzburg' => 'Ballbusters Würzburg',
								'Rocky Rolling Wheels Berlin' => 'Rocky Rolling Wheels Berlin',
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
							'parent_repeater'   => 'field_6380d0a06bcf5',
						),
						array(
							'key'               => 'field_6380d0a0d5f00',
							'label'             => 'Mannschaft 2',
							'name'              => 'mannschaft_2',
							'aria-label'        => '',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'Hurricanes Bochum'    => 'Hurricanes Bochum',
								'Flash Tigers'         => 'Flash Tigers',
								'Ruhr Rollers Essen'   => 'Ruhr Rollers Essen',
								'Ballbusters Würzburg' => 'Ballbusters Würzburg',
								'Rocky Rolling Wheels Berlin' => 'Rocky Rolling Wheels Berlin',
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
							'parent_repeater'   => 'field_6380d0a06bcf5',
						),
						array(
							'key'               => 'field_6380c58d5689d',
							'label'             => '1. Schiedsrichter',
							'name'              => '1_schiedsrichter',
							'aria-label'        => '',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'Gennadi Hill'      => 'Gennadi Hill',
								'Richard Loch-Karl' => 'Richard Loch-Karl',
								'Paul Kirste'       => 'Paul Kirste',
								'Leonie Mülheims'   => 'Leonie Mülheims',
								'Mirco Albers'      => 'Mirco Albers',
								'Reinhold Goltz'    => 'Reinhold Goltz',
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
							'parent_repeater'   => 'field_6380c58cccd21',
						),
						array(
							'key'               => 'field_6380c58d5a341',
							'label'             => '2. Schiedsrichter',
							'name'              => '2_schiedsrichter',
							'aria-label'        => '',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'Gennadi Hill'      => 'Gennadi Hill',
								'Richard Loch-Karl' => 'Richard Loch-Karl',
								'Paul Kirste'       => 'Paul Kirste',
								'Leonie Mülheims'   => 'Leonie Mülheims',
								'Mirco Albers'      => 'Mirco Albers',
								'Reinhold Goltz'    => 'Reinhold Goltz',
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
							'parent_repeater'   => 'field_6380c58cccd21',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'acf/spielplan2liga',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_6380a05a66bab',
			'title'                 => 'Block: Bundesliga Spielplan1',
			'fields'                => array(
				array(
					'key'               => 'field_6380a05b3653a',
					'label'             => 'Zeile',
					'name'              => 'row',
					'aria-label'        => '',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => '',
					'min'               => 0,
					'max'               => 0,
					'layout'            => 'table',
					'button_label'      => 'Eintrag hinzufügen',
					'rows_per_page'     => 20,
					'sub_fields'        => array(
						array(
							'key'               => 'field_6380a05b8a445',
							'label'             => 'Spielnummer',
							'name'              => 'spielnummer',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
							'parent_repeater'   => 'field_6380a05b3653a',
						),
						array(
							'key'               => 'field_6380a7501a964',
							'label'             => 'Zeit',
							'name'              => 'zeit',
							'aria-label'        => '',
							'type'              => 'time_picker',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'display_format'    => 'H:i',
							'return_format'     => 'H:i',
							'parent_repeater'   => 'field_6380a05b3653a',
						),
						array(
							'key'               => 'field_6380a05b8def4',
							'label'             => 'Mannschaft 1',
							'name'              => 'mannschaft_1',
							'aria-label'        => '',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'Black Knights Dreieich 1' => 'Black Knights Dreieich 1',
								'Black Knights Dreieich 2' => 'Black Knights Dreieich 2',
								'Star Drivers Bad Kreuznach' => 'Star Drivers Bad Kreuznach',
								'Rolli Teufel Ludwigshafen' => 'Rolli Teufel Ludwigshafen',
								'Munich Animals'           => 'Munich Animals',
								'Nording Bulls Lalendorf'  => 'Nording Bulls Lalendorf',
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
							'parent_repeater'   => 'field_6380a05b3653a',
						),
						array(
							'key'               => 'field_6380a3fd95975',
							'label'             => 'Mannschaft 2',
							'name'              => 'mannschaft_2',
							'aria-label'        => '',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'Black Knights Dreieich 1' => 'Black Knights Dreieich 1',
								'Black Knights Dreieich 2' => 'Black Knights Dreieich 2',
								'Star Drivers Bad Kreuznach' => 'Star Drivers Bad Kreuznach',
								'Rolli Teufel Ludwigshafen' => 'Rolli Teufel Ludwigshafen',
								'Munich Animals'           => 'Munich Animals',
								'Nording Bulls Lalendorf'  => 'Nording Bulls Lalendorf',
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
							'parent_repeater'   => 'field_6380a05b3653a',
						),
						array(
							'key'               => 'field_6380a4716a46b',
							'label'             => 'Ergebnis',
							'name'              => 'ergebnis',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
							'parent_repeater'   => 'field_6380a05b3653a',
						),
						array(
							'key'               => 'field_6380a4c0e8bad',
							'label'             => '(HZ)',
							'name'              => 'hz',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
							'parent_repeater'   => 'field_6380a05b3653a',
						),
						array(
							'key'               => 'field_6380a4d1e8bae',
							'label'             => '1. Schiedsrichter',
							'name'              => '1_schiedsrichter',
							'aria-label'        => '',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices' => array(
								'Waldemar Ulrich' => 'Waldemar Ulrich',
								'Gennadi Hill' => 'Gennadi Hill',
								'Gerd Autenrieth' => 'Gerd Autenrieth',
								'Gerd Menz' => 'Gerd Menz',
								'Paul Kirste' => 'Paul Kirste',
								'Nadir Mohamed' => 'Nadir Mohamed',
								'Christoph Respondek' => 'Christoph Respondek',
								'Jürgen Erdmann-Feix' => 'Jürgen Erdmann-Feix',
								'Ralf Buree' => 'Ralf Buree',
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
							'parent_repeater'   => 'field_6380a05b3653a',
						),
						array(
							'key'               => 'field_6380a4ede8baf',
							'label'             => '2. Schiedsrichter',
							'name'              => '2_schiedsrichter',
							'aria-label'        => '',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices' => array(
								'Waldemar Ulrich' => 'Waldemar Ulrich',
								'Gennadi Hill' => 'Gennadi Hill',
								'Gerd Autenrieth' => 'Gerd Autenrieth',
								'Gerd Menz' => 'Gerd Menz',
								'Paul Kirste' => 'Paul Kirste',
								'Nadir Mohamed' => 'Nadir Mohamed',
								'Christoph Respondek' => 'Christoph Respondek',
								'Jürgen Erdmann-Feix' => 'Jürgen Erdmann-Feix',
								'Ralf Buree' => 'Ralf Buree',
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
							'parent_repeater'   => 'field_6380a05b3653a',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'acf/spielplan-1liga',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_6380c58c82a94',
			'title'                 => 'Block: Bundesliga Spielplan2',
			'fields'                => array(
				array(
					'key'               => 'field_6380c58cccd21',
					'label'             => 'Zeile',
					'name'              => 'row',
					'aria-label'        => '',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => '',
					'min'               => 0,
					'max'               => 0,
					'layout'            => 'table',
					'button_label'      => 'Eintrag hinzufügen',
					'rows_per_page'     => 20,
					'sub_fields'        => array(
						array(
							'key'               => 'field_6380c58d40959',
							'label'             => 'Spielnummer',
							'name'              => 'spielnummer',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
							'parent_repeater'   => 'field_6380c58cccd21',
						),
						array(
							'key'               => 'field_6380c58d4440b',
							'label'             => 'Zeit',
							'name'              => 'zeit',
							'aria-label'        => '',
							'type'              => 'time_picker',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'display_format'    => 'H:i',
							'return_format'     => 'H:i',
							'parent_repeater'   => 'field_6380c58cccd21',
						),
						array(
							'key'               => 'field_6380c58d47ea2',
							'label'             => 'Mannschaft 1',
							'name'              => 'mannschaft_1',
							'aria-label'        => '',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'Hurricanes Bochum'    => 'Hurricanes Bochum',
								'Flash Tigers'         => 'Flash Tigers',
								'Ruhr Rollers Essen'   => 'Ruhr Rollers Essen',
								'Ballbusters Würzburg' => 'Ballbusters Würzburg',
								'Rocky Rolling Wheels Berlin' => 'Rocky Rolling Wheels Berlin',
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
							'parent_repeater'   => 'field_6380c58cccd21',
						),
						array(
							'key'               => 'field_6380c58d4b944',
							'label'             => 'Mannschaft 2',
							'name'              => 'mannschaft_2',
							'aria-label'        => '',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'Hurricanes Bochum'    => 'Hurricanes Bochum',
								'Flash Tigers'         => 'Flash Tigers',
								'Ruhr Rollers Essen'   => 'Ruhr Rollers Essen',
								'Ballbusters Würzburg' => 'Ballbusters Würzburg',
								'Rocky Rolling Wheels Berlin' => 'Rocky Rolling Wheels Berlin',
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
							'parent_repeater'   => 'field_6380c58cccd21',
						),
						array(
							'key'               => 'field_6380c58d4f2a3',
							'label'             => 'Ergebnis',
							'name'              => 'ergebnis',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
							'parent_repeater'   => 'field_6380c58cccd21',
						),
						array(
							'key'               => 'field_6380c58d52dfa',
							'label'             => '(HZ)',
							'name'              => 'hz',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
							'parent_repeater'   => 'field_6380c58cccd21',
						),
						array(
							'key'               => 'field_6380c58d5689d',
							'label'             => '1. Schiedsrichter',
							'name'              => '1_schiedsrichter',
							'aria-label'        => '',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'Gennadi Hill'      => 'Gennadi Hill',
								'Richard Loch-Karl' => 'Richard Loch-Karl',
								'Paul Kirste'       => 'Paul Kirste',
								'Leonie Mülheims'   => 'Leonie Mülheims',
								'Mirco Albers'      => 'Mirco Albers',
								'Reinhold Goltz'    => 'Reinhold Goltz',
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
							'parent_repeater'   => 'field_6380c58cccd21',
						),
						array(
							'key'               => 'field_6380c58d5a341',
							'label'             => '2. Schiedsrichter',
							'name'              => '2_schiedsrichter',
							'aria-label'        => '',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'Gennadi Hill'      => 'Gennadi Hill',
								'Richard Loch-Karl' => 'Richard Loch-Karl',
								'Paul Kirste'       => 'Paul Kirste',
								'Leonie Mülheims'   => 'Leonie Mülheims',
								'Mirco Albers'      => 'Mirco Albers',
								'Reinhold Goltz'    => 'Reinhold Goltz',
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
							'parent_repeater'   => 'field_6380c58cccd21',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'acf/spielplan-2liga',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => 0,
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5e75fe4703777',
			'title'                 => 'Block: E-Mail-Formular',
			'fields'                => array(
				array(
					'key'               => 'field_5e76005adfdbf',
					'label'             => 'Formular',
					'name'              => 'form',
					'aria-label'        => '',
					'type'              => 'post_object',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'post_type'         => array(
						0 => 'forms',
					),
					'taxonomy'          => '',
					'allow_null'        => 0,
					'multiple'          => 0,
					'return_format'     => 'id',
					'ui'                => 1,
				),
				array(
					'key'               => 'field_5e75ff37dfdbc',
					'label'             => 'Empfänger',
					'name'              => 'recipients',
					'aria-label'        => '',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => '',
					'min'               => 1,
					'max'               => 0,
					'layout'            => 'block',
					'button_label'      => 'Empfänger hinzufügen',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5e75ff8adfdbd',
							'label'             => 'Empfänger',
							'name'              => 'recipient',
							'aria-label'        => '',
							'type'              => 'email',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'parent_repeater'   => 'field_5e75ff37dfdbc',
						),
					),
					'rows_per_page'     => 20,
				),
				array(
					'key'               => 'field_5e76000ddfdbe',
					'label'             => 'Mailtext',
					'name'              => 'mailtext',
					'aria-label'        => '',
					'type'              => 'wysiwyg',
					'instructions'      => 'Felddaten können mit [Feldname] eingefügt werden. - z. B. [Vorname]',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'tabs'              => 'all',
					'toolbar'           => 'full',
					'media_upload'      => 0,
					'delay'             => 0,
				),
				array(
					'key'               => 'field_5e7774aeb6335',
					'label'             => 'Absender',
					'name'              => 'from_email',
					'aria-label'        => '',
					'type'              => 'email',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'acf/cmailform',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => false,
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5ea00d0056de9',
			'title'                 => 'Block: Feed Them Social Shortcode',
			'fields'                => array(
				array(
					'key'               => 'field_5ea00d60f743e',
					'label'             => 'Feed Them Social Shortcode',
					'name'              => 'fts_shortcode',
					'aria-label'        => '',
					'type'              => 'textarea',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'maxlength'         => '',
					'rows'              => '',
					'new_lines'         => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'acf/fts-shortcode',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => false,
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5e720dae6f36b',
			'title'                 => 'Block: Icon',
			'fields'                => array(
				array(
					'key'               => 'field_5e720e08f66c1',
					'label'             => 'Icon',
					'name'              => 'icon',
					'aria-label'        => '',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'id',
					'preview_size'      => 'medium',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
				array(
					'key'               => 'field_5e720e33f66c2',
					'label'             => 'Name',
					'name'              => 'name',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5e720e5bf66c3',
					'label'             => 'Position',
					'name'              => 'position',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'acf/icon',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => false,
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5ea952fcad296',
			'title'                 => 'Block: Kachel Logo',
			'fields'                => array(

				array(
					'key'               => 'field_5ea95504952ec',
					'label'             => 'Überschrift',
					'name'              => 'title',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5ea95504952ec1',
					'label'             => 'Text',
					'name'              => 'text',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_6106c12834f32',
					'label'             => 'logo',
					'name'              => 'logos',
					'aria-label'        => '',
					'type'              => 'repeater',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'collapsed'         => '',
					'min'               => 0,
					'max'               => 0,
					'layout'            => 'block',
					'button_label'      => 'Eintrag hinzufügen',
					'sub_fields'        => array(
						array(
							'key'               => 'field_6106cd85149a0',
							'label'             => 'bild',
							'name'              => 'image',
							'aria-label'        => '',
							'type'              => 'image',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'return_format'     => 'array',
							'preview_size'      => 'medium',
							'library'           => 'all',
							'min_width'         => '',
							'min_height'        => '',
							'min_size'          => '',
							'max_width'         => '',
							'max_height'        => '',
							'max_size'          => '',
							'mime_types'        => '',
							'parent_repeater'   => 'field_6106c12834f32',
						),
						array(
							'key'               => 'field_6106a12dc9861',
							'label'             => 'Link',
							'name'              => 'url',
							'aria-label'        => '',
							'type'              => 'url',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'parent_repeater'   => 'field_6106c12834f32',
						),
						array(
							'key'               => 'field_6106b14dde929',
							'label'             => 'Linkauswahl',
							'name'              => 'linkauswahl',
							'aria-label'        => '',
							'type'              => 'select',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'choices'           => array(
								'&nbsp;'          => 'Intern Link',
								'target="_blank"' => 'Extrem Link',
							),
							'default_value'     => false,
							'allow_null'        => 0,
							'multiple'          => 0,
							'ui'                => 0,
							'return_format'     => 'value',
							'ajax'              => 0,
							'placeholder'       => '',
							'parent_repeater'   => 'field_6106c12834f32',
						),
					),
					'rows_per_page'     => 20,
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'acf/tile-vertical-bild',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => false,
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_6106ab76934a3',
			'title'                 => 'Block: Kachel mit Link',
			'fields'                => array(
				array(
					'key'               => 'field_6106ab7714248',
					'label'             => 'Bildtyp',
					'name'              => 'img_type',
					'aria-label'        => '',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'file' => 'Datei',
						'post' => 'Beitragsbild',
					),
					'default_value'     => false,
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_6106ab7717ce9',
					'label'             => 'Bild',
					'name'              => 'img_id',
					'aria-label'        => '',
					'type'              => 'image',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_6106ab7714248',
								'operator' => '==',
								'value'    => 'file',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'id',
					'preview_size'      => 'medium',
					'library'           => 'all',
					'min_width'         => '',
					'min_height'        => '',
					'min_size'          => '',
					'max_width'         => '',
					'max_height'        => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
				array(
					'key'               => 'field_6106ab7726776',
					'label'             => 'Überschrift',
					'name'              => 'title',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_6106ab772a21b',
					'label'             => 'Inhalt',
					'name'              => 'content',
					'aria-label'        => '',
					'type'              => 'wysiwyg',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'tabs'              => 'all',
					'toolbar'           => 'full',
					'media_upload'      => 0,
					'delay'             => 0,
				),
				array(
					'key'               => 'field_6106ab772dcbf',
					'label'             => 'Link',
					'name'              => 'obj_id',
					'aria-label'        => '',
					'type'              => 'post_object',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'post_type'         => '',
					'taxonomy'          => '',
					'allow_null'        => 0,
					'multiple'          => 0,
					'return_format'     => 'object',
					'ui'                => 1,
				),
				array(
					'key'               => 'field_6106ab7731763',
					'label'             => 'Button',
					'name'              => 'btn_select',
					'aria-label'        => '',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'none'       => 'Keinen Button',
						'default'    => 'Button mit Standardtext (mehr)',
						'individual' => 'Button mit eigenem Text',
					),
					'default_value'     => false,
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
				array(
					'key'               => 'field_6106ab773521c',
					'label'             => 'Individueller Buttontext',
					'name'              => 'btn_text',
					'aria-label'        => '',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_6106ab7731763',
								'operator' => '==',
								'value'    => 'individual',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_6106ab7738cb8',
					'label'             => 'Buttonstil',
					'name'              => 'btn_style',
					'aria-label'        => '',
					'type'              => 'select',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => array(
						array(
							array(
								'field'    => 'field_6106ab7731763',
								'operator' => '!=',
								'value'    => 'none',
							),
						),
					),
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'default' => 'Standard',
						'fancy'   => 'Ausgefallen',
					),
					'default_value'     => false,
					'allow_null'        => 0,
					'multiple'          => 0,
					'ui'                => 0,
					'return_format'     => 'value',
					'ajax'              => 0,
					'placeholder'       => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'acf/tile-vertical',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => false,
		)
	);



	acf_add_local_field_group(
		array(
			'key'                   => 'group_5e87013226224',
			'title'                 => 'Datenschutz-Einstellungen',
			'fields'                => array(
				array(
					'key'               => 'field_5e87019f2a0d6',
					'label'             => 'Matomo',
					'name'              => 'ww_privacy_matomo',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5e8701e02a0d7',
							'label'             => 'Aktivieren',
							'name'              => 'act',
							'aria-label'        => '',
							'type'              => 'true_false',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'message'           => '',
							'default_value'     => 0,
							'ui'                => 0,
							'ui_on_text'        => '',
							'ui_off_text'       => '',
						),
						array(
							'key'               => 'field_5e8702272a0d8',
							'label'             => 'Code',
							'name'              => 'code',
							'aria-label'        => '',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => array(
								array(
									array(
										'field'    => 'field_5e8701e02a0d7',
										'operator' => '==',
										'value'    => '1',
									),
								),
							),
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'maxlength'         => '',
							'rows'              => '',
							'new_lines'         => '',
						),
					),
				),
				array(
					'key'               => 'field_5e8704be90a51',
					'label'             => 'YouTube',
					'name'              => 'ww_privacy_youtube',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5e870147b8fa9',
							'label'             => 'Aktivieren',
							'name'              => 'act',
							'aria-label'        => '',
							'type'              => 'true_false',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'message'           => '',
							'default_value'     => 0,
							'ui'                => 0,
							'ui_on_text'        => '',
							'ui_off_text'       => '',
						),
					),
				),
				array(
					'key'               => 'field_5ea00aeaf1b8f',
					'label'             => 'Feed Them Social',
					'name'              => 'ww_privacy_fts',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5ea00b58f1b90',
							'label'             => 'Aktivieren',
							'name'              => 'act',
							'aria-label'        => '',
							'type'              => 'true_false',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'message'           => '',
							'default_value'     => 0,
							'ui'                => 0,
							'ui_on_text'        => '',
							'ui_off_text'       => '',
						),
					),
				),
				array(
					'key'               => 'field_5e8aea184e481',
					'label'             => 'Einstellungen',
					'name'              => 'ww_privacy_settings',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5e8aeaab4e482',
							'label'             => 'Impressum',
							'name'              => 'imprint_url',
							'aria-label'        => '',
							'type'              => 'page_link',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'post_type'         => array(
								0 => 'page',
							),
							'taxonomy'          => '',
							'allow_null'        => 0,
							'allow_archives'    => 0,
							'multiple'          => 0,
						),
						array(
							'key'               => 'field_5e8ad9e8ea433',
							'label'             => 'Datenschutzerklärung',
							'name'              => 'privacy_url',
							'aria-label'        => '',
							'type'              => 'page_link',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'post_type'         => array(
								0 => 'page',
							),
							'taxonomy'          => '',
							'allow_null'        => 0,
							'allow_archives'    => 0,
							'multiple'          => 0,
						),
						array(
							'key'               => 'field_5e8aeb0c4e483',
							'label'             => 'Erklärung zur Barrierefreiheit',
							'name'              => 'accessibility_url',
							'aria-label'        => '',
							'type'              => 'page_link',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'post_type'         => array(
								0 => 'page',
							),
							'taxonomy'          => '',
							'allow_null'        => 0,
							'allow_archives'    => 0,
							'multiple'          => 0,
						),
						array(
							'key'               => 'field_5e8ada6dea434',
							'label'             => 'Text',
							'name'              => 'text',
							'aria-label'        => '',
							'type'              => 'textarea',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'maxlength'         => '',
							'rows'              => '',
							'new_lines'         => '',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'options_page',
						'operator' => '==',
						'value'    => 'privacy-settings',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'seamless',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => false,
		)
	);

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5e748e6a32a64',
			'title'                 => 'Formularfelder',
			'fields'                => array(
				array(
					'key'               => 'field_5e748e9ccee8f',
					'label'             => 'Standardfelder',
					'name'              => 'standard_fields',
					'aria-label'        => '',
					'type'              => 'checkbox',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'choices'           => array(
						'firstname' => 'Vorname',
						'lastname'  => 'Nachname',
						'email'     => 'E-Mail',
					),
					'allow_custom'      => 0,
					'default_value'     => array(),
					'layout'            => 'vertical',
					'toggle'            => 0,
					'return_format'     => 'value',
					'save_custom'       => 0,
				),
				array(
					'key'               => 'field_5e74991c2e3cb',
					'label'             => 'Extrafelder',
					'name'              => 'extra_fields',
					'aria-label'        => '',
					'type'              => 'flexible_content',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layouts'           => array(
						'layout_5e749930abeb6' => array(
							'key'        => 'layout_5e749930abeb6',
							'name'       => 'textfields',
							'label'      => 'Textfelder',
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_5e74c38d0abb8',
									'label'             => 'Textfelder',
									'name'              => 'textfields',
									'aria-label'        => '',
									'type'              => 'repeater',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'collapsed'         => '',
									'min'               => 1,
									'max'               => 0,
									'layout'            => 'block',
									'button_label'      => 'Textfeld hinzufügen',
									'sub_fields'        => array(
										array(
											'key'          => 'field_5e7499892e3cc',
											'label'        => 'Name',
											'name'         => 'name',
											'aria-label'   => '',
											'type'         => 'text',
											'instructions' => '',
											'required'     => 1,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'default_value' => '',
											'placeholder'  => '',
											'prepend'      => '',
											'append'       => '',
											'maxlength'    => '',
											'parent_repeater' => 'field_5e74c38d0abb8',
										),
										array(
											'key'          => 'field_5e7499b82e3cd',
											'label'        => 'Pflichtfeld',
											'name'         => 'mandatory',
											'aria-label'   => '',
											'type'         => 'true_false',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'message'      => '',
											'default_value' => 0,
											'ui'           => 0,
											'ui_on_text'   => '',
											'ui_off_text'  => '',
											'parent_repeater' => 'field_5e74c38d0abb8',
										),
										array(
											'key'          => 'field_5ea6c23a6e67f',
											'label'        => 'Typ',
											'name'         => 'type',
											'aria-label'   => '',
											'type'         => 'select',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'choices'      => array(
												'text'  => 'Text',
												'email' => 'E-Mail',
												'tel'   => 'Telefon',
											),
											'default_value' => false,
											'allow_null'   => 0,
											'multiple'     => 0,
											'ui'           => 0,
											'return_format' => 'value',
											'ajax'         => 0,
											'placeholder'  => '',
											'parent_repeater' => 'field_5e74c38d0abb8',
										),
										array(
											'key'          => 'field_5ea6c2c66e680',
											'label'        => 'Auto-Vervollständigung',
											'name'         => 'autocomplete',
											'aria-label'   => '',
											'type'         => 'select',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'choices'      => array(
												'default' => 'Standard',
												'off'     => 'Aus',
												'given-name' => 'Vorname',
												'family-name' => 'Nachname',
												'address-line1' => 'Straße',
												'address-line2' => 'Adresszusatz',
												'postal-code' => 'PLZ',
												'address-level2' => 'Ort',
												'tel-national' => 'Telefon (national) Typ text',
												'tel'     => 'Telefon (international) Typ tel',
												'email'   => 'E-Mail Typ email',
											),
											'default_value' => false,
											'allow_null'   => 0,
											'multiple'     => 0,
											'ui'           => 0,
											'return_format' => 'value',
											'ajax'         => 0,
											'placeholder'  => '',
											'parent_repeater' => 'field_5e74c38d0abb8',
										),
									),
									'rows_per_page'     => 20,
								),
							),
							'min'        => '',
							'max'        => '',
						),
						'layout_5e749ae47e190' => array(
							'key'        => 'layout_5e749ae47e190',
							'name'       => 'checkboxes',
							'label'      => 'Checkboxen',
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_5e749b287e191',
									'label'             => 'Checkboxen',
									'name'              => 'checkboxes',
									'aria-label'        => '',
									'type'              => 'repeater',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'collapsed'         => '',
									'min'               => 1,
									'max'               => 0,
									'layout'            => 'block',
									'button_label'      => 'Checkbox hinzufügen',
									'sub_fields'        => array(
										array(
											'key'          => 'field_5e749b647e192',
											'label'        => 'Name',
											'name'         => 'name',
											'aria-label'   => '',
											'type'         => 'text',
											'instructions' => '',
											'required'     => 1,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'default_value' => '',
											'placeholder'  => '',
											'prepend'      => '',
											'append'       => '',
											'maxlength'    => '',
											'parent_repeater' => 'field_5e749b287e191',
										),
										array(
											'key'          => 'field_5e749b907e193',
											'label'        => 'Pflichtfeld',
											'name'         => 'mandatory',
											'aria-label'   => '',
											'type'         => 'true_false',
											'instructions' => '',
											'required'     => 0,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'message'      => '',
											'default_value' => 0,
											'ui'           => 0,
											'ui_on_text'   => '',
											'ui_off_text'  => '',
											'parent_repeater' => 'field_5e749b287e191',
										),
									),
									'rows_per_page'     => 20,
								),
							),
							'min'        => '',
							'max'        => '',
						),
						'layout_5e749be77e194' => array(
							'key'        => 'layout_5e749be77e194',
							'name'       => 'radioboxes',
							'label'      => 'Radioboxen',
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_5e76313e97411',
									'label'             => 'Gruppenname',
									'name'              => 'groupname',
									'aria-label'        => '',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => '',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_5e749be77e195',
									'label'             => 'Radioboxen',
									'name'              => 'radioboxes',
									'aria-label'        => '',
									'type'              => 'repeater',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'collapsed'         => '',
									'min'               => 1,
									'max'               => 0,
									'layout'            => 'block',
									'button_label'      => 'Radiobox hinzufügen',
									'sub_fields'        => array(
										array(
											'key'          => 'field_5e749be77e196',
											'label'        => 'Name',
											'name'         => 'name',
											'aria-label'   => '',
											'type'         => 'text',
											'instructions' => '',
											'required'     => 1,
											'conditional_logic' => 0,
											'wrapper'      => array(
												'width' => '',
												'class' => '',
												'id'    => '',
											),
											'default_value' => '',
											'placeholder'  => '',
											'prepend'      => '',
											'append'       => '',
											'maxlength'    => '',
											'parent_repeater' => 'field_5e749be77e195',
										),
									),
									'rows_per_page'     => 20,
								),
								array(
									'key'               => 'field_5e749be77e197',
									'label'             => 'Pflichtfelder',
									'name'              => 'mandatory',
									'aria-label'        => '',
									'type'              => 'true_false',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'message'           => '',
									'default_value'     => 0,
									'ui'                => 0,
									'ui_on_text'        => '',
									'ui_off_text'       => '',
								),
							),
							'min'        => '',
							'max'        => '',
						),
						'layout_5e776fa63e468' => array(
							'key'        => 'layout_5e776fa63e468',
							'name'       => 'message',
							'label'      => 'Nachricht',
							'display'    => 'block',
							'sub_fields' => array(
								array(
									'key'               => 'field_5e776fd13e469',
									'label'             => 'Name',
									'name'              => 'name',
									'aria-label'        => '',
									'type'              => 'text',
									'instructions'      => '',
									'required'          => 1,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'default_value'     => 'Nachricht',
									'placeholder'       => '',
									'prepend'           => '',
									'append'            => '',
									'maxlength'         => '',
								),
								array(
									'key'               => 'field_5e77701a3e46a',
									'label'             => 'Pflichtfeld',
									'name'              => 'mandatory',
									'aria-label'        => '',
									'type'              => 'true_false',
									'instructions'      => '',
									'required'          => 0,
									'conditional_logic' => 0,
									'wrapper'           => array(
										'width' => '',
										'class' => '',
										'id'    => '',
									),
									'message'           => '',
									'default_value'     => 0,
									'ui'                => 0,
									'ui_on_text'        => '',
									'ui_off_text'       => '',
								),
							),
							'min'        => '',
							'max'        => '',
						),
					),
					'button_label'      => 'Felder hinzufügen',
					'min'               => '',
					'max'               => '',
				),
				array(
					'key'               => 'field_5e77691573c49',
					'label'             => 'Datenschutz',
					'name'              => 'privacy_fields',
					'aria-label'        => '',
					'type'              => 'group',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'layout'            => 'block',
					'sub_fields'        => array(
						array(
							'key'               => 'field_5e77696773c4a',
							'label'             => 'Text vor Link',
							'name'              => 'text_before',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
						array(
							'key'               => 'field_5e77698173c4b',
							'label'             => 'Link',
							'name'              => 'link',
							'aria-label'        => '',
							'type'              => 'page_link',
							'instructions'      => '',
							'required'          => 1,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'post_type'         => array(
								0 => 'page',
							),
							'taxonomy'          => '',
							'allow_null'        => 0,
							'allow_archives'    => 0,
							'multiple'          => 0,
						),
						array(
							'key'               => 'field_5e776c5c01749',
							'label'             => 'Text nach Link',
							'name'              => 'text_after',
							'aria-label'        => '',
							'type'              => 'text',
							'instructions'      => '',
							'required'          => 0,
							'conditional_logic' => 0,
							'wrapper'           => array(
								'width' => '',
								'class' => '',
								'id'    => '',
							),
							'default_value'     => '',
							'placeholder'       => '',
							'prepend'           => '',
							'append'            => '',
							'maxlength'         => '',
						),
					),
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'post_type',
						'operator' => '==',
						'value'    => 'forms',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
			'show_in_rest'          => false,
		)
	);

	acf_add_local_field_group(array(
		'key' => 'group_62387306a76a4',
		'title' => 'Veranstaltungs-Kategorien Bild',
		'fields' => array(
			array(
				'key' => 'field_62387328bcb6f',
				'label' => 'img',
				'name' => 'img',
				'aria-label' => '',
				'type' => 'image',
				'instructions' => '',
				'required' => 0,
				'conditional_logic' => 0,
				'wrapper' => array(
					'width' => '',
					'class' => '',
					'id' => '',
				),
				'return_format' => 'id',
				'library' => 'all',
				'min_width' => '',
				'min_height' => '',
				'min_size' => '',
				'max_width' => '',
				'max_height' => '',
				'max_size' => '',
				'mime_types' => '',
				'preview_size' => 'medium',
			),
		),
		'location' => array(
			array(
				array(
					'param' => 'taxonomy',
					'operator' => '==',
					'value' => 'tribe_events_cat',
				),
			),
		),
		'menu_order' => 0,
		'position' => 'normal',
		'style' => 'default',
		'label_placement' => 'top',
		'instruction_placement' => 'label',
		'hide_on_screen' => '',
		'active' => true,
		'description' => '',
		'show_in_rest' => 0,
	));

	acf_add_local_field_group(
		array(
			'key'                   => 'group_5ef467b88b26c',
			'title'                 => 'Block: Download-Button',
			'fields'                => array(
				array(
					'key'               => 'field_5ef4681018eca',
					'label'             => 'Titel',
					'name'              => 'title',
					'type'              => 'text',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'default_value'     => '',
					'placeholder'       => '',
					'prepend'           => '',
					'append'            => '',
					'maxlength'         => '',
				),
				array(
					'key'               => 'field_5ef4683918ecb',
					'label'             => 'Datei',
					'name'              => 'file',
					'type'              => 'file',
					'instructions'      => '',
					'required'          => 1,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'return_format'     => 'array',
					'library'           => 'all',
					'min_size'          => '',
					'max_size'          => '',
					'mime_types'        => '',
				),
				array(
					'key'               => 'field_5ef483452eb6a',
					'label'             => 'Barrierefrei? (Nur für PDF)',
					'name'              => 'accessible',
					'type'              => 'true_false',
					'instructions'      => '',
					'required'          => 0,
					'conditional_logic' => 0,
					'wrapper'           => array(
						'width' => '',
						'class' => '',
						'id'    => '',
					),
					'message'           => '',
					'default_value'     => 0,
					'ui'                => 0,
					'ui_on_text'        => '',
					'ui_off_text'       => '',
				),
			),
			'location'              => array(
				array(
					array(
						'param'    => 'block',
						'operator' => '==',
						'value'    => 'acf/btn-download',
					),
				),
			),
			'menu_order'            => 0,
			'position'              => 'normal',
			'style'                 => 'default',
			'label_placement'       => 'top',
			'instruction_placement' => 'label',
			'hide_on_screen'        => '',
			'active'                => true,
			'description'           => '',
		)
	);

	acf_add_local_field_group(array(
	'key' => 'group_642ebddc5765d',
	'title' => 'Block: YouTube',
	'fields' => array(
		array(
			'key' => 'field_642ebddc06a0c',
			'label' => 'YouTube Link',
			'name' => 'oembed',
			'aria-label' => '',
			'type' => 'oembed',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'width' => 640,
			'height' => 390,
		),
		array(
			'key' => 'field_642ec0ab5e63f',
			'label' => 'Overlay-Bild *',
			'name' => 'img',
			'aria-label' => '',
			'type' => 'image',
			'instructions' => '',
			'required' => 1,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
			'preview_size' => 'medium',
		),
		array(
			'key' => 'field_642ec15b5e640',
			'label' => 'Datenschutztext',
			'name' => 'text',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/youtube',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

acf_add_local_field_group(array(
	'key' => 'group_6454d28c5c004',
	'title' => 'betterplace.org',
	'fields' => array(
		array(
			'key' => 'field_6454d28c25417',
			'label' => 'Überschrift',
			'name' => 'headline',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
		array(
			'key' => 'field_6454d2c525418',
			'label' => 'Projekt ID',
			'name' => 'projekt_id',
			'aria-label' => '',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'maxlength' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'block',
				'operator' => '==',
				'value' => 'acf/betterplace',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));


endif;
